### ISSUE TITLE
Timeout only works if cssFile is true

### ISSUE THREAD

**Issue by hmaesta** [Maronato/vue-toastification#107]
#### Versions
- 1.7.6

#### Describe the bug
If `cssFile` is `false`, the `timeout` option is ignored.

#### Expected behavior
Toast element should be destroyed.

#### Steps to reproduce

1. Set `toast` config like:

```js
  toast: {
    timeout: 2000,
    icon: false,
    cssFile: false
  },
```

2. Open a toast and watch it exist forever.

Nuxt sandbox: 
→ https://codesandbox.io/s/frosty-bash-5rc8r?file=/nuxt.config.js

**Comment by Maronato** [comment]
Hello! Thank you for reporting this.

The timeout event is triggered by an `animationend` event caused by the progress bar:
https://github.com/Maronato/vue-toastification/blob/96c6a5f4e630a5ad1fe9cdbad15aa8ef308a9a00/src/components/VtProgressBar.vue#L39

Because of that, since you did not include the style, there is no animation defined for the progress bar and the timeout won't work as you expect it to.

To fix it, you'll need to at least add a simple animation to `.Vue-Toastification__progress-bar`, e.g.:
```css
@keyframes scale-x-frames {
  0% {
    transform: scaleX(1);
  }
  100% {
    transform: scaleX(0);
  }
}
.Vue-Toastification__progress-bar {
  animation: scale-x-frames linear 1 forwards;
}
```

Here is a demo of it working:
![CleanShot 2020-07-10 at 11 11 48](https://user-images.githubusercontent.com/19658460/87163722-30594700-c29e-11ea-81c4-016a71da9d0d.gif)

[![Edit happy-margulis-of0kb](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-margulis-of0kb?fontsize=14&hidenavigation=1&theme=dark)
