### ISSUE TITLE
Why extra columns are defined?

### ISSUE THREAD

**Issue by igorpopryadukhin** [Maronato/vue-toastification#163]
## Versions

-^1.7.8

![image](https://user-images.githubusercontent.com/48174353/105629697-9e89e380-5e55-11eb-98c9-e5628cfad50b.png)

I would like not to clutter up with extra columns, is it possible?

**Comment by Maronato** [comment]
I'm sorry about that. The columns are necessary for they are the containers wherein toasts are displayed.
Users can't interact with them, however, so there shouldn't be any issues regarding usability.
If they still bother you, you can always disable them through css. For instance, to only keep the `top-right` column, do:
```css
.Vue-Toastification__container.top-left,
.Vue-Toastification__container.top-center,
.Vue-Toastification__container.bottom-left,
.Vue-Toastification__container.bottom-center,
.Vue-Toastification__container.bottom-right {
  display: none;
}
```
