### ISSUE TITLE
[v2] Toaster with Timeout breaks when css animations disabled - should not be dependent on css animation for dismissal

### ISSUE THREAD

**Issue by mathiash98** [Maronato/vue-toastification#166]
## Versions
- 2.0-rc.1

## Describe the bug
Toaster does not appear when timeout is set if global css styles have "disabled" animations.
```CSS
@media (prefers-reduced-motion: reduce) {
  * {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}
```
alternative css rules that breaks the timeout
```CSS
animation-play-state: paused !important;
transition: none !important;
scroll-behavior: auto !important;
```

## Expected behavior
Toaster should not be dependent on trigger from css animation. It should use an internal javascript method instead.

## Steps to reproduce
https://codesandbox.io/s/vue3-forked-8oxrp?file=/src/App.vue

## Your Environment
- Vue 3.0.5
- vue-toastification 2.0.0-rc.1
